name = "cloudflare-d1"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cloudflare-d1"
database_id = "1d728253-e6ab-4ca8-a5e8-8f35acb678a9"
